### ISSUE TITLE
Créer dans le routeur le chemin pour ?user=

### ISSUE THREAD

**Issue by mikhawa** [WebDevCF2m2021/NewsWebPrepaTest#48]
`controller/routerController.php`

Il faut rajouter une condition permettant de détecter l’existence de la variable $_GET['user'] en vérifiant qu'il s'agit bien d'un int (non signé),
- Dans ce cas, il faudra charger la méthode  `theuserSelectOneById` venant de `theuserManager.php`
- Si jamais on reçoit false, affichage de l'erreur 404 avec : Utilisateur inconnu
- Si on récupère l'utilisateur:
1. Récupérer la méthode chargeant les articles écris par cet utilisateur (idem que sur la page blog), en utilisant la méthode venant de `thearticleManager.php` : thearticleSelectAllByIdUser();
2. Si pas d'article, écrire: "cet utilisateur n'a pas écrit d'article"
3. lien vers la vue `user.html.twig` en passant l'utilisateur
4. Si articles, on fait une boucle pour les afficher comme sur ?blog, sans le nom à chaque article

**Comment by SashaKlash** [comment]
Hey, les gars, on peut communiquer par ici pour échanger (par exemple les différents noms de variables qui pourraient être utiles dans plusieurs fichiers.
Likez si vous avez vu ce message.
